name: Manage Github Actions

on:
    workflow_dispatch: 

env:
    passphraseFile: ${{ secrets.FILE_PASS_PHRASE }}

jobs:    
    DecryptFile:
      runs-on: ubuntu-latest   
      
      steps:
      - uses: actions/checkout@v2
      - name: Decrypt and read file
        run: gpg --quiet --batch --yes --decrypt --passphrase="$passphraseFile" --output $HOME/payload.json upsertSecretsAndVars.json.gpg
        
      - name: Print file content
        run: cat $HOME/payload.json