name: Manage Github Actions

on:
    workflow_dispatch: 

jobs:
    Decrypt-file:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Decrypt and read file
            run: gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.FILE_PASS_PHRASE }} --output $HOME/payload.json upsertSecretsAndVars.json.gpg
            - name: Print file content
            run: cat $HOME/payload.json

